---
- name: set timezone to New York
  timezone:
    name: America/New_York

- include_tasks: packages.yml

- include_tasks: firewall.yml

- name: set up logrotate
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.conf
