---
- include_tasks: timezone.yml

- include_tasks: packages.yml

- include_tasks: firewall.yml

- include_tasks: users.yml

- include_tasks: logrotate.yml

- include_tasks: motd.yml

- include_tasks: monitoring.yml # Currently only Openstack hosts are supported
  when:
    - '"watchtower" not in group_names' # No need to install CheckMK agent on the CheckMK control host
    - ansible_facts['virtualization_type']|lower != "virtualbox" # Exclude Vagrant setups
#    - ansible_facts['virtualization_type']|lower != "xen" # Exclude AWS
#    - ansible_facts['system_vendor']|lower != "Amazon EC2" # Exclude AWS
    - ansible_facts['virtualization_type']|lower == "openstack" # Only include Openstack
