---
- name: set timezone to New York
  timezone:
    name: America/New_York

- include_tasks: packages.yml

- include_tasks: firewall.yml

- include_tasks: users.yml

- name: set up logrotate
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.conf

- name: set up motd
  template:
    src: motd.j2
    dest: /etc/motd
    mode: 0777
