---
- name: Install epel-release
  yum:
    -epel-release
  state: latest

- name: Install packages
  yum: 
    name: 
    - git
    - openssl
    - python2-pip
    - vim-enhanced
    #- yum-security  # This is RedHat only
    state: latest

- name: Update
  yum:
    name: '*'
    bugfix: true
    state: latest

- pip:
    name: pip
    state: latest
