---
- include_tasks: timezone.yml

- include_tasks: packages.yml

- include_tasks: firewall.yml

- include_tasks: users.yml

- include_tasks: logrotate.yml

- include_tasks: motd.yml

- include_tasks: monitoring.yml
  when: '"watchtower" not in group_names' # No need to install CheckMK agent on the CheckMK control host
