---
- name: Install epel
  yum: 
    name: 
    - epel-release
    - git
    - openssl
    - python2-pip
    - vim-enhanced
    - yum-security
    state: latest

- name: Update
  yum:
    name: '*'
    bugfix: true
    state: latest

- pip:
    name: pip
    state: latest
