---
- name: Install high level repositories
  yum:
    name:
      - epel-release
      - centos-release-scl
    state: latest

- name: Install other packages
  yum:
    name:
      - awscli
      - bzip2-devel
      - bind-utils
      - centos-release-scl
      - epel-release
      - firewalld
      - gdbm-devel
      - gcc
      - gcc-c++
      - git
      - htop
      - libffi-devel
      - libxslt-devel
      - libyaml-devel
      - lsof
      - man-pages
      - nano
      - nfs-utils
      - ncurses-devel
      - make
      - openssl-devel
      - patch
      - readline-devel
      - python2-pip
      - rh-python36
      - sqlite-devel
      - zlib-devel
      - unzip
      - zip
    state: latest

- name: Update all packages
  yum:
    name: '*'
    state: latest

- name: Enable Python 3 as default
  template:
    src: rh-python36.sh.j2
    dest: /etc/profile.d/rh-python36.sh

- name: Update Python 3 pip
  shell: "source /opt/rh/rh-python36/enable && pip install --upgrade pip"

- name: Reload systemd daemon
  command: "systemctl daemon-reload"
