---
# Default groups
- name: Ensure group dlib exists
  group:
    name: dlib
    state: present
    system: true
    gid: 200

# Users
- name: Add users
  user:
    name: "{{ item.name }}"
    comment: "{{ item.gecos }}"
    uid: "{{ item.uid }}"
    #group: "{{ item.name }}"
    groups: "{{ item.groups }}"
    state: "{{ item.state }}"
    remove: "{{ item.remove }}"
  #with_items: "{{ users }}"
  loop: "{{ users|flatten(levels=1) }}"
  when: item.name  == "flannon" or item.name == "derrick"
 
